-- Production-shaped local development starts empty by design.
-- Create charities and publish operational configuration through /admin so
-- every visible value has an accountable source instead of demo fixtures.
