packages:
  - apps/*
  - packages/*

supportedArchitectures:
  os: [current]
  cpu: [arm64, x64]

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild

patchedDependencies:
  expo-modules-jsi@57.0.6: patches/expo-modules-jsi@57.0.6.patch
