import type { ImpactWeek } from "@screen-time/contracts";

export const demoImpactWeek: ImpactWeek = {
  id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  weekStart: "2026-08-17",
  weekEnd: "2026-08-23",
  status: "open",
  currency: "USD",
  grossRevenueMinor: 2_302_600,
  impactFundMinor: 1_842_100,
  impactPercentage: 80,
  isEstimated: true,
  participants: 4_281,
  rewardedAds: 18_903,
  donationProofUrl: null,
  candidates: [
    {
      charity: {
        id: "11111111-1111-4111-8111-111111111111",
        name: "Ocean Conservancy",
        logoUrl: null,
        shortDescription: "Protecting the ocean from today's greatest challenges.",
        website: "https://oceanconservancy.org",
        country: "United States",
        category: "environment",
      },
      votes: 1_798,
      percentage: 42,
      selectedByCurrentUser: false,
    },
    {
      charity: {
        id: "22222222-2222-4222-8222-222222222222",
        name: "Doctors Without Borders",
        logoUrl: null,
        shortDescription: "Independent medical humanitarian assistance worldwide.",
        website: "https://www.doctorswithoutborders.org",
        country: "International",
        category: "health",
      },
      votes: 1_456,
      percentage: 34,
      selectedByCurrentUser: false,
    },
    {
      charity: {
        id: "33333333-3333-4333-8333-333333333333",
        name: "Rainforest Trust",
        logoUrl: null,
        shortDescription: "Safeguarding threatened rainforests and wildlife.",
        website: "https://www.rainforesttrust.org",
        country: "International",
        category: "environment",
      },
      votes: 1_027,
      percentage: 24,
      selectedByCurrentUser: false,
    },
  ],
};
