// GENERATED by scripts/android-guide/build.mjs — do not edit by hand.
// Real captures of Android Accessibility settings; the ring is drawn from these
// fractions by AndroidGuideImage, never burned into the image.
import type { ImageSourcePropType } from "react-native";

export type AndroidGuideId = "accessibility-find-still" | "accessibility-turn-on" | "accessibility-allow";

export type AndroidGuideAsset = {
  source: ImageSourcePropType;
  aspectRatio: number;
  highlight: { x: number; y: number; width: number; height: number };
};

export const ANDROID_GUIDE_IMAGES: Record<AndroidGuideId, AndroidGuideAsset> = {
  "accessibility-find-still": {
    source: require("../../assets/android-guide/accessibility-find-still.png"),
    aspectRatio: 2.7273,
    highlight: { x: 0.037, y: 0.2702, width: 0.9259, height: 0.4444 },
  },
  "accessibility-turn-on": {
    source: require("../../assets/android-guide/accessibility-turn-on.png"),
    aspectRatio: 1.35,
    highlight: { x: 0.7546, y: 0.6687, width: 0.1852, height: 0.21 },
  },
  "accessibility-allow": {
    source: require("../../assets/android-guide/accessibility-allow.png"),
    aspectRatio: 0.9153,
    highlight: { x: 0.0463, y: 0.7814, width: 0.9074, height: 0.161 },
  },
};
