// Generated by scripts/shortcut-guide/build.swift from spec.json. Do not edit by hand.
// Real captures of Apple's Shortcuts app (iOS 26) and where to tap on each one.

import type { ImageSourcePropType } from "react-native";

/** Position and size as fractions of the image, so they scale with it. */
export type GuideHighlight = {
left: number;
top: number;
width: number;
height: number;
};

export type GuideImage = {
source: ImageSourcePropType;
aspectRatio: number;
/** In the order the user taps them. */
highlights: GuideHighlight[];
};

export const SHORTCUT_GUIDE_IMAGES = {
  "auto-01-app-trigger": {
    source: require("../../assets/shortcut-guide/auto-01-app-trigger.jpg"),
    aspectRatio: 1.6041,
    highlights: [
      { left: 0.0738, top: 0.7592, width: 0.7023, height: 0.1918 },
      { left: 0.0509, top: 0.3469, width: 0.8982, height: 0.2449 },
    ],
  },
  "auto-02-choose": {
    source: require("../../assets/shortcut-guide/auto-02-choose.jpg"),
    aspectRatio: 2.0904,
    highlights: [
      { left: 0.7379, top: 0.6968, width: 0.1985, height: 0.2021 },
    ],
  },
  "auto-03-pick-app": {
    source: require("../../assets/shortcut-guide/auto-03-pick-app.jpg"),
    aspectRatio: 1.9848,
    highlights: [
      { left: 0.0356, top: 0.7374, width: 0.9288, height: 0.2525 },
      { left: 0.8372, top: 0.0455, width: 0.1323, height: 0.2626 },
    ],
  },
  "auto-04-run-immediately": {
    source: require("../../assets/shortcut-guide/auto-04-run-immediately.jpg"),
    aspectRatio: 1.5352,
    highlights: [
      { left: 0.0509, top: 0.5703, width: 0.8982, height: 0.1953 },
      { left: 0.7226, top: 0.7969, width: 0.1934, height: 0.1484 },
      { left: 0.7939, top: 0.0469, width: 0.1781, height: 0.1797 },
    ],
  },
  "auto-05-create-new": {
    source: require("../../assets/shortcut-guide/auto-05-create-new.jpg"),
    aspectRatio: 1.5352,
    highlights: [
      { left: 0.0356, top: 0.5078, width: 0.4224, height: 0.4531 },
    ],
  },
  "auto-06-search-actions": {
    source: require("../../assets/shortcut-guide/auto-06-search-actions.jpg"),
    aspectRatio: 2.3963,
    highlights: [
      { left: 0.0611, top: 0.6280, width: 0.8779, height: 0.2927 },
    ],
  },
  "auto-07-pick-action": {
    source: require("../../assets/shortcut-guide/auto-07-pick-action.jpg"),
    aspectRatio: 1.4343,
    highlights: [
      { left: 0.0458, top: 0.7555, width: 0.9084, height: 0.2044 },
    ],
  },
  "auto-08-pick-name": {
    source: require("../../assets/shortcut-guide/auto-08-pick-name.jpg"),
    aspectRatio: 2.6554,
    highlights: [
      { left: 0.3613, top: 0.4324, width: 0.6005, height: 0.2838 },
    ],
  },
  "auto-09-save": {
    source: require("../../assets/shortcut-guide/auto-09-save.jpg"),
    aspectRatio: 2.1593,
    highlights: [
      { left: 0.8372, top: 0.0495, width: 0.1323, height: 0.2857 },
    ],
  },
  "return-01-open-app": {
    source: require("../../assets/shortcut-guide/return-01-open-app.jpg"),
    aspectRatio: 1.6107,
    highlights: [
      { left: 0.0611, top: 0.7459, width: 0.8779, height: 0.2213 },
    ],
  },
  "return-02-choose-app": {
    source: require("../../assets/shortcut-guide/return-02-choose-app.jpg"),
    aspectRatio: 2.7292,
    highlights: [
      { left: 0.3028, top: 0.6111, width: 0.1425, height: 0.2361 },
      { left: 0.2545, top: 0.0694, width: 0.4835, height: 0.2639 },
    ],
  },
  "return-03-rename": {
    source: require("../../assets/shortcut-guide/return-03-rename.jpg"),
    aspectRatio: 1.4664,
    highlights: [
      { left: 0.2137, top: 0.0672, width: 0.5903, height: 0.1642 },
    ],
  },
} satisfies Record<string, GuideImage>;

export type GuideImageId = keyof typeof SHORTCUT_GUIDE_IMAGES;
