#!/usr/bin/env node
// Builds Still's real-capture Android setup guide: crops raw screenshots to the
// relevant region and writes a manifest of ring targets as fractions, so the app
// draws the ring itself and the JPEGs stay unannotated (mirrors the iOS guide in
// scripts/shortcut-guide/build.swift).
//
// Usage: node scripts/android-guide/build.mjs /path/to/raw-captures
// Raw captures are full-screen `adb exec-out screencap -p` PNGs named in spec.json.
// Requires ffmpeg on PATH. Raw captures are not committed; the cropped assets and
// the generated manifest are.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const mobileRoot = resolve(here, "..", "..");
const rawDir = process.argv[2];
if (!rawDir) {
  console.error("Usage: node scripts/android-guide/build.mjs /path/to/raw-captures");
  process.exit(1);
}

const spec = JSON.parse(readFileSync(join(here, "spec.json"), "utf8"));
const outDir = join(mobileRoot, "assets", "android-guide");
mkdirSync(outDir, { recursive: true });

const entries = [];
for (const image of spec.images) {
  const [cx, cy, cw, ch] = image.crop;
  const [hx, hy, hw, hh] = image.highlight;
  const source = join(rawDir, image.source);
  const out = join(outDir, `${image.id}.png`);
  execFileSync("ffmpeg", ["-y", "-v", "error", "-i", source, "-vf", `crop=${cw}:${ch}:${cx}:${cy}`, out]);
  entries.push({
    id: image.id,
    aspectRatio: Number((cw / ch).toFixed(4)),
    highlight: {
      x: Number(((hx - cx) / cw).toFixed(4)),
      y: Number(((hy - cy) / ch).toFixed(4)),
      width: Number((hw / cw).toFixed(4)),
      height: Number((hh / ch).toFixed(4)),
    },
  });
}

const ts = `// GENERATED by scripts/android-guide/build.mjs — do not edit by hand.
// Real captures of Android Accessibility settings; the ring is drawn from these
// fractions by AndroidGuideImage, never burned into the image.
import type { ImageSourcePropType } from "react-native";

export type AndroidGuideId = ${entries.map((e) => `"${e.id}"`).join(" | ")};

export type AndroidGuideAsset = {
  source: ImageSourcePropType;
  aspectRatio: number;
  highlight: { x: number; y: number; width: number; height: number };
};

export const ANDROID_GUIDE_IMAGES: Record<AndroidGuideId, AndroidGuideAsset> = {
${entries
  .map(
    (e) => `  "${e.id}": {
    source: require("../../assets/android-guide/${e.id}.png"),
    aspectRatio: ${e.aspectRatio},
    highlight: { x: ${e.highlight.x}, y: ${e.highlight.y}, width: ${e.highlight.width}, height: ${e.highlight.height} },
  },`,
  )
  .join("\n")}
};
`;
writeFileSync(join(mobileRoot, "src", "components", "android-guide-assets.ts"), ts);
console.log(`Wrote ${entries.length} guide images to assets/android-guide and android-guide-assets.ts`);
